# Site settings
title: Corcd Blog
SEOTitle: 人生路途中的旅人 | Corcd Blog
header-img: img/home-bg.jpg
email: whzcorcd@gmail.com
description: " 人生路途中的旅人 | 王含泽，One HZNUer & Web Amateur  | 这里是 @corcd 的个人博客，与你一起发现更大的世界。"
keyword: "王含泽, whzcorcd, corcd, @corcd,  王含泽的博客, Corcd Blog, 博客, 个人网站, 互联网, Web"
url: "https://corcd.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'
timezone: CN                           # fix the time
# fadeIn: true

# SNS settings
RSS: false
weibo_username:     WWhhzz1
zhihu_username:     NULL
github_username:    corcd
twitter_username:   whzcorcd
# facebook_username:  
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# plugins: (older: gem：)
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: corcd

# Netease setttings
netease_comment: false

# UY setttings
UY_comment: false


# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-108349396-1'            # Format: UA-xxxxxx-xx
ga_domain: https://corcd.github.io/



# Sidebar settings
sidebar: true
sidebar-owner: Corcd                          # whether or not using Sidebar.
sidebar-about-description: " 学习，乐寓其中<br>路漫漫其修远兮"
sidebar-avatar: /img/avatar-me.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "乱序",
        href: "http://mida.re/"
    },{
        title: "前端外刊评论",
        href: "http://qianduan.guru/"
    },{
        title: "前端神盾局",
        href: "http://wepiaofei.github.io/blog/"
    }
]
